package com.quiambao.mypetstore.inventory;

import java.math.BigDecimal;
import java.util.List;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
public class CatalogDataSeeder implements CommandLineRunner {

    private final AnimalCategoryRepository categoryRepository;
    private final AnimalRepository animalRepository;

    public CatalogDataSeeder(AnimalCategoryRepository categoryRepository, AnimalRepository animalRepository) {
        this.categoryRepository = categoryRepository;
        this.animalRepository = animalRepository;
    }

    @Override
    @Transactional
    public void run(String... args) {
        // Clear existing data to allow re-seeding with new schema
        animalRepository.deleteAll();

        AnimalCategory dogs = ensureCategory("Dogs");
        AnimalCategory cats = ensureCategory("Cats");
        AnimalCategory birds = ensureCategory("Birds");
        AnimalCategory fishes = ensureCategory("Fishes");

        // DOGS
        animalRepository.save(new Animal("Golden Retriever", "Dog", "Retriever", "2 years", "A truly magnificent companion! This golden beauty is the ultimate family dog. Known for their incredible gentle nature, intelligence, and unwavering loyalty, Golden Retrievers are perfect for active families who love outdoor adventures. They're excellent swimmers, friendly with children and other pets, and have that signature happy disposition that melts hearts instantly. These dogs are highly trainable and make wonderful therapy and service animals. Get ready for endless cuddles, playful games in the park, and pure unconditional love!", new BigDecimal("1200.00"), 3, List.of("https://placedog.net/600/400?id=1", "https://placedog.net/600/400?id=2", "https://placedog.net/600/400?id=3"), true, dogs));
        animalRepository.save(new Animal("Labrador Retriever", "Dog", "Retriever", "1.5 years", "Meet your new best friend! Labradors are America's favorite dog breed for a reason. These athletic, intelligent, and incredibly loving pups are perfect for active families. Labs are natural swimmers, fantastic at retrieving, and have an infectious enthusiasm for life. They're extremely smart, easy to train, and have gentle temperaments that make them ideal with kids and other animals. Whether you're looking for a jogging buddy, a cuddle companion, or a loyal friend, this Lab checks all the boxes. Their playful antics and boundless affection will keep you laughing for years to come!", new BigDecimal("1100.00"), 4, List.of("https://placedog.net/600/400?id=4", "https://placedog.net/600/400?id=5"), true, dogs));
        animalRepository.save(new Animal("German Shepherd", "Dog", "Shepherd", "2 years", "Intelligence meets loyalty in this noble German Shepherd! These magnificent dogs are renowned for their exceptional intelligence, courage, and unwavering devotion to their families. German Shepherds are highly trainable and excel as working dogs, but they're just as wonderful as loving family companions. They're incredibly protective, alert, and responsive to training. These dogs require mental and physical stimulation to thrive, making them perfect for active owners who appreciate their dynamic personality. With proper socialization and training, German Shepherds become the most dedicated and steadfast friends you could ask for.", new BigDecimal("1400.00"), 2, List.of("https://placedog.net/600/400?id=6", "https://placedog.net/600/400?id=7"), false, dogs));
        animalRepository.save(new Animal("French Bulldog", "Dog", "Bulldog", "1 year", "Compact charm with a huge personality! French Bulldogs are the perfect urban companion. These adorable muscular bundles of joy have big personalities despite their small stature. Frenchies are incredibly affectionate, entertaining, and don't require excessive exercise, making them ideal for apartment living. They're known for their silly antics, charming way of tilting their heads, and their relentless demand for cuddles and attention. With their playful temperament and minimal grooming needs, they're fantastic for first-time dog owners. Be prepared for endless entertainment and a loyal shadow that follows you everywhere!", new BigDecimal("1600.00"), 2, List.of("https://placedog.net/600/400?id=8", "https://placedog.net/600/400?id=9"), true, dogs));
        animalRepository.save(new Animal("Beagle", "Dog", "Hound", "1.5 years", "Curiosity meets adventure with this energetic Beagle! Beagles are the ultimate explorers with their incredible sense of smell and boundless energy. These small but mighty hunters are perfect for families who enjoy outdoor activities and want an enthusiastic companion. Beagles are incredibly social, pack-oriented, and thrive with other dogs and families. They're intelligent but can be stubborn, which makes training both a challenge and an adventure. Their playful personality, distinctive howl, and heart-melting brown eyes make them irresistibly charming. If you want a dog that keeps life interesting and exciting, a Beagle is your perfect match!", new BigDecimal("900.00"), 5, List.of("https://placedog.net/600/400?id=10", "https://placedog.net/600/400?id=11"), false, dogs));

        // CATS
        animalRepository.save(new Animal("Maine Coon", "Cat", "Maine Coon", "2 years", "The gentle giant of the feline world! Maine Coons are one of the largest domestic cat breeds, but their size belies their sweet and gentle nature. These impressive cats can weigh up to 18 pounds and have luxurious, long, fluffy coats. Despite their majestic appearance, Maine Coons are exceptionally affectionate, playful, and social creatures. They're known for their dog-like personalities, love of water, and tendency to greet owners at the door like puppies. These intelligent cats are great with families and other pets and will follow you around the house. Be ready for a loving, funny, and magnificent companion that will steal everyone's hearts!", new BigDecimal("1300.00"), 2, List.of("https://loremflickr.com/600/400/mainecoon,cat?lock=1", "https://loremflickr.com/600/400/mainecoon,cat?lock=2"), true, cats));
        animalRepository.save(new Animal("Persian Cat", "Cat", "Persian", "1.5 years", "Elegance and grace personified! Persian cats are the royalty of the cat world with their luxuriously long, flowing coats and distinctive flat faces. These calm, gentle souls prefer a peaceful environment and love lounging in sunny windows. Persians are incredibly affectionate but at their own pace—they'll choose when they want cuddles and attention. Their serene temperament makes them perfect for quiet households or elderly owners. Their beautiful almond-shaped eyes and sweet expression create an almost mystical allure. Regular grooming keeps their stunning coat in pristine condition. If you want a sophisticated, loving, and beautiful companion, a Persian is your perfect choice!", new BigDecimal("1100.00"), 3, List.of("https://loremflickr.com/600/400/persiancat?lock=3", "https://loremflickr.com/600/400/persiancat?lock=4"), false, cats));
        animalRepository.save(new Animal("Bengal Cat", "Cat", "Bengal", "1 year", "Wild beauty meets domestic charm! Bengal cats are absolutely stunning with their spectacular spotted or marbled coats that resemble mini leopards. These exotic-looking felines are incredibly energetic, playful, and intelligent. Bengals are known for their acrobatic abilities, curiosity, and their love for interactive play and climbing. They form strong bonds with their owners and are quite vocal, often having lengthy conversations with you. Bengals are perfect for active people who want a cat with personality and pizzazz. They love water, enjoy learning tricks, and thrive on mental stimulation. Get ready for a lively, entertaining, and breathtakingly beautiful companion!", new BigDecimal("1800.00"), 1, List.of("https://loremflickr.com/600/400/bengalcat?lock=5", "https://loremflickr.com/600/400/bengalcat?lock=6"), true, cats));
        animalRepository.save(new Animal("Siamese Cat", "Cat", "Siamese", "2 years", "Stunning and vocal—the supermodel with a personality! Siamese cats are instantly recognizable with their striking blue almond-shaped eyes, sleek cream and chocolate point coloring, and triangular ear shape. These cats are exceptionally intelligent, curious, and extremely vocal—they have absolutely no qualms about telling you exactly what they think! Siamese are highly social and demand attention and interaction from their owners. They love being involved in everything you do and can become depressed if left alone for long periods. These affectionate cats are incredibly loyal, playful, and will follow you from room to room. If you want a chatty, loving, and stunningly beautiful cat, the Siamese is perfect!", new BigDecimal("950.00"), 4, List.of("https://loremflickr.com/600/400/siamesecat?lock=7", "https://loremflickr.com/600/400/siamesecat?lock=8"), false, cats));
        animalRepository.save(new Animal("British Shorthair", "Cat", "British Shorthair", "1.5 years", "Charming teddy bear with a calm disposition! British Shorthairs are stocky, sturdy cats with round faces that give them an adorably cute expression, almost like a teddy bear come to life. These calm, laid-back felines are perfect for relaxed households and are known for their even temperament and quiet nature. British Shorthairs are independent but affectionate, preferring to be near you without constantly demanding attention. They're content entertaining themselves, watching birds from windows, or lounging on comfortable furniture. Their plush, short coats come in various colors including the famous blue-gray. These good-natured cats are wonderful with children and other pets. Perfect for anyone seeking a peaceful, loving, and low-maintenance feline companion!", new BigDecimal("1050.00"), 3, List.of("https://loremflickr.com/600/400/britishshorthair?lock=9", "https://loremflickr.com/600/400/britishshorthair?lock=10"), false, cats));

        // BIRDS
        animalRepository.save(new Animal("Macaw", "Bird", "Macaw", "3 years", "A brilliant explosion of color and personality! Macaws are among the most spectacular and intelligent birds, with their vibrant rainbow-colored plumage that absolutely commands attention. These magnificent parrots are incredibly social, affectionate, and can live for 50+ years—making them a true lifelong companion. Macaws are highly intelligent and can learn tricks, words, and even understand complex commands. They're playful, mischievous, and incredibly entertaining to watch. These birds form deep bonds with their owners and require significant daily interaction and mental stimulation. Their loud vocalizations and need for spacious cages mean they're best suited for dedicated bird enthusiasts. If you're ready for an extraordinary companion that will bring joy and dazzling beauty to your life, a Macaw is unmatched!", new BigDecimal("2500.00"), 1, List.of("https://loremflickr.com/600/400/macaw,bird?lock=11", "https://loremflickr.com/600/400/macaw,bird?lock=12"), true, birds));
        animalRepository.save(new Animal("Cockatoo", "Bird", "Cockatoo", "2 years", "Charismatic charm with a dramatic flair! Cockatoos are stunningly beautiful birds with their distinctive crests and predominantly white plumage. These highly social and emotional birds crave attention and interaction to a remarkable degree. Cockatoos are incredibly playful, can live 40-60 years, and form exceptionally strong bonds with their owners. They have big personalities, a love for physical affection like head scratches, and an impressive ability to mimic sounds and learn tricks. Their loud vocalizations and need for constant engagement mean they require dedicated owners. Cockatoos can be demanding but reward you with unconditional affection and endless entertainment. Their dramatic displays and silly antics will have you laughing daily. Perfect for experienced bird enthusiasts seeking an interactive and devoted feathered friend!", new BigDecimal("2000.00"), 2, List.of("https://loremflickr.com/600/400/cockatoo,bird?lock=13", "https://loremflickr.com/600/400/cockatoo,bird?lock=14"), false, birds));
        animalRepository.save(new Animal("Lovebird", "Bird", "Lovebird", "1 year", "Tiny treasures bursting with personality! Lovebirds are small but absolutely adorable colorful parrots that are perfect for bird beginners. These social little acrobats are playful, energetic, and enjoy interaction with their owners. Lovebirds are known for their incredible loyalty and mate for life, forming beautiful pair bonds. They bring vibrant colors, charming personalities, and delightful chirping to any home. These intelligent little birds can learn to perform simple tricks and enjoy toys and foraging activities. They require moderate daily interaction and a stimulating environment with toys to keep them happy. Despite their small size, their entertaining antics and affectionate nature make them beloved companions. If you want a beautiful, loyal, and entertaining feathered friend that's more manageable than larger parrots, Lovebirds are perfect!", new BigDecimal("400.00"), 8, List.of("https://loremflickr.com/600/400/lovebird?lock=15", "https://loremflickr.com/600/400/lovebird?lock=16"), false, birds));
        animalRepository.save(new Animal("Parakeet", "Bird", "Parakeet", "6 months", "Colorful bundles of joy for the whole family! Parakeets are small, adorable, and incredibly playful birds that make fantastic starter birds for families and first-time bird owners. These charming little acrobats come in beautiful color combinations including blue, green, yellow, and white. Parakeets are social, curious creatures that love interactive play and can learn to whistle tunes and mimic words. They're active, entertaining to watch, and their playful antics will have everyone smiling. These intelligent birds enjoy toys, mirrors, and foraging activities to keep their minds engaged. Parakeets are relatively low-maintenance compared to larger parrots and can live 10-15 years with proper care. They chirp cheerfully throughout the day, bringing energy and joy to your home. The perfect feathered friend for anyone seeking a colorful, interactive, and delightful companion!", new BigDecimal("250.00"), 12, List.of("https://loremflickr.com/600/400/parakeet?lock=17", "https://loremflickr.com/600/400/parakeet?lock=18"), true, birds));
        animalRepository.save(new Animal("Canary", "Bird", "Canary", "1 year", "A singing sensation of pure sunshine! Canaries are beloved for their breathtakingly beautiful melodious songs and gorgeous bright yellow plumage. These charming songbirds fill your home with delightful natural music and are perfect for those who appreciate the beauty of bird song. Canaries are relatively independent compared to social parrots, making them ideal for people who want a bird without requiring constant interaction. They're beautiful to watch, entertaining with their playful movements, and require moderate care. The males are particularly known for their stunning vocal abilities. Canaries appreciate spacious cages where they can fly and engage in natural behaviors. They live 10-15 years and bring consistent joy through their beautiful songs and cheerful presence. Perfect for anyone who wants a low-maintenance, melodious, and visually stunning feathered companion!", new BigDecimal("150.00"), 6, List.of("https://loremflickr.com/600/400/canary,bird?lock=19", "https://loremflickr.com/600/400/canary,bird?lock=20"), false, birds));

        // FISHES
        animalRepository.save(new Animal("Betta Fish", "Fish", "Siamese Fighting Fish", "1 year", "A living jewel for your aquarium! Betta fish are absolute superstars of the aquarium world, renowned for their spectacular flowing fins and brilliant colors. Males especially display iridescent hues ranging from deep reds, blues, greens, and golds that shimmer and change depending on light and mood. These intelligent fish have distinct personalities and recognize their owners, often coming to the surface when you approach the tank. Bettas are interactive and will flare their fins, jump, and perform for you. Their beauty is matched only by their spirited nature and individual character. Important note: Males must be kept alone as they're aggressively territorial. Perfect for anyone wanting a low-maintenance but visually stunning and interactive fish companion!", new BigDecimal("85.00"), 15, List.of("https://loremflickr.com/600/400/bettafish?lock=21", "https://loremflickr.com/600/400/bettafish?lock=22"), true, fishes));
        animalRepository.save(new Animal("Goldfish", "Fish", "Goldfish", "2 years", "The classic beauty that started it all! Goldfish are iconic aquatic pets beloved for generations. These hardy, low-maintenance fish are perfect for beginners and seasoned aquarists alike. Despite their reputation as 'starter fish,' goldfish are more intelligent and long-lived than many realize—they can live 10-40 years with proper care and can grow quite large. Goldfish are active, playful fish that come in stunning colors from brilliant gold to white, black, and calico patterns. They're interactive and recognize their owners, often creating a bond with you. Goldfish feel more spacious tanks to thrive and appreciate a variety of plants and decorations to explore. Their simple beauty and hardiness make them wonderful companions for anyone seeking a reliable and beautiful aquatic pet!", new BigDecimal("45.00"), 20, List.of("https://loremflickr.com/600/400/goldfish?lock=23", "https://loremflickr.com/600/400/goldfish?lock=24"), false, fishes));
        animalRepository.save(new Animal("Neon Tetra", "Fish", "Tetra", "6 months", "Tiny diamonds that light up your aquarium! Neon Tetras are absolutely stunning little fish famous for their brilliant electric blue stripe running the length of their body and vibrant red coloring on their lower half. These peaceful schooling fish are a favorite among aquarists for their breathtaking beauty and graceful swimming patterns. Neon Tetras are best kept in groups where they display their natural schooling behavior, creating mesmerizing visual displays as they move in synchronized patterns. These small, community-friendly fish are perfect for planted aquariums and peaceful tank environments. Watching a school of Neon Tetras glide through your tank is absolutely hypnotic and creates a sense of tranquility. Their minimal care requirements and stunning appearance make them accessible yet spectacular. Perfect for anyone wanting beautiful, interactive, and easy-to-care-for fish!", new BigDecimal("15.00"), 50, List.of("https://loremflickr.com/600/400/neontetra?lock=25", "https://loremflickr.com/600/400/neontetra?lock=26"), false, fishes));
        animalRepository.save(new Animal("Angelfish", "Fish", "Angelfish", "1 year", "Graceful elegance captured in aquatic form! Angelfish are absolutely stunning with their distinctive triangular shape, flowing fins, and elegant movements. These captivating fish seem to float through the water with an almost ethereal grace. Angelfish display intricate stripe patterns in black, white, gold, and silver combinations, making each fish a living work of art. These intelligent and interactive fish recognize their owners and respond to feeding time with enthusiasm. Angelfish are more active and engaging than many aquarium fish, making them entertaining to observe. They prefer larger tanks where they can fully express their graceful movements. With proper conditions and compatible tank mates, Angelfish create a living centerpiece in any aquarium. Perfect for aquarists seeking an elegant, interactive, and visually remarkable fish companion!", new BigDecimal("35.00"), 10, List.of("https://loremflickr.com/600/400/angelfish?lock=27", "https://loremflickr.com/600/400/angelfish?lock=28"), true, fishes));
        animalRepository.save(new Animal("Clownfish", "Fish", "Clownfish", "1.5 years", "The famous 'Finding Nemo' star in your tank! Clownfish are instantly recognizable with their striking orange body and brilliant white stripes with black outlines. These playful, interactive fish are small but have huge personalities and remarkable intelligence. Clownfish are famous for their symbiotic relationship with anemones, but they can also thrive in community tanks. They're curious, bold, and will interact with their tank mates and owners with surprising personality. Clownfish display distinct behaviors and hierarchies within groups, making them fascinating to observe and study. Their bright, cheerful coloring brings instant joy to any aquarium. These hardy, engaging fish are perfect for anyone wanting a captivating sea-inspired companion that brings vibrancy and personality to their aquatic environment!", new BigDecimal("120.00"), 8, List.of("https://loremflickr.com/600/400/clownfish?lock=29", "https://loremflickr.com/600/400/clownfish?lock=30"), true, fishes));
    }

    private AnimalCategory ensureCategory(String name) {
        return categoryRepository.findByNameIgnoreCase(name)
                .orElseGet(() -> categoryRepository.save(new AnimalCategory(name, SlugUtils.slugify(name))));
    }
}
